In [1]:
name = 'Mr.Squeaky'
name

'Mr.Squeaky'

In [2]:
name = "Mr. Squeaky"
print(name)

Mr. Squeaky

In [3]:
name = 'Mr. Squeaky'
print(name)

Mr. Squeaky

In [5]:
name = "Mr. Squeaky"
name

'Mr. Squeaky'

In [7]:
x = 10
print(x)

10

In [16]:
x = 10
x

10

In [ ]:
*Task 2:*

In [15]:
bayes_age = 4.0
favorite_toy = "Mr. Squeaky"
owner = 'DataCamp'

#Printing:
print(bayes_age)
print(favorite_toy)
print(owner)

4.0
Mr. Squeaky
DataCamp

In [ ]:
*Task 3:*

In [23]:
import pandas as pd

df = pd.read_csv("mpr.csv")

In [24]:
df.head()

  Dog Name             Owner Name         Dog Breed         Status  Age
0    Bayes               DataCamp  Golden Retriever  Still Missing    1
1  Sigmoid                    NaN         Dachshund  Still Missing    2
2   Sparky             Dr. Apache     Border Collie          Found    3
3  Theorem  Joseph-Louis Lagrange    French Bulldog          Found    4
4      Ned           Tim Oliphant          Shih Tzu  Still Missing    2

In [25]:
len(df)

6

In [28]:
print("First 5 rows:")
df.head()

First 5 rows:

  Dog Name             Owner Name         Dog Breed         Status  Age
0    Bayes               DataCamp  Golden Retriever  Still Missing    1
1  Sigmoid                    NaN         Dachshund  Still Missing    2
2   Sparky             Dr. Apache     Border Collie          Found    3
3  Theorem  Joseph-Louis Lagrange    French Bulldog          Found    4
4      Ned           Tim Oliphant          Shih Tzu  Still Missing    2

In [32]:
print('First 5 rows:')
print(df.head())

First 5 rows:
  Dog Name             Owner Name         Dog Breed         Status  Age
0    Bayes               DataCamp  Golden Retriever  Still Missing    1
1  Sigmoid                    NaN         Dachshund  Still Missing    2
2   Sparky             Dr. Apache     Border Collie          Found    3
3  Theorem  Joseph-Louis Lagrange    French Bulldog          Found    4
4      Ned           Tim Oliphant          Shih Tzu  Still Missing    2

In [33]:
print('Total no. of rows:' , len(df))

Total no. of rows: 6

In [34]:
print('\nTotal no. of rows:' , len(df))

Total no. of rows: 6

In [36]:
selected_columns = df[['Dog Name' , 'Status']]
print(selected_columns)

  Dog Name         Status
0    Bayes  Still Missing
1  Sigmoid  Still Missing
2   Sparky          Found
3  Theorem          Found
4      Ned  Still Missing
5    Benny          Found

In [43]:
selected_columns = df[["Dog Name", 'Dog Breed']]
selected_columns

  Dog Name         Dog Breed
0    Bayes  Golden Retriever
1  Sigmoid         Dachshund
2   Sparky     Border Collie
3  Theorem    French Bulldog
4      Ned          Shih Tzu
5    Benny            Poodle

In [40]:
still_missing_dogs = df['Status'] == 'Still Missing'
still_missing_dogs

0     True
1     True
2    False
3    False
4     True
5    False
Name: Status, dtype: bool

In [39]:
still_missing_dogs = df[df['Status'] == 'Still Missing']
still_missing_dogs

  Dog Name    Owner Name         Dog Breed         Status  Age
0    Bayes      DataCamp  Golden Retriever  Still Missing    1
1  Sigmoid           NaN         Dachshund  Still Missing    2
4      Ned  Tim Oliphant          Shih Tzu  Still Missing    2

In [44]:
not_poodle = df["Dog Breed"] != 'Poodle'
not_poodle

0     True
1     True
2     True
3     True
4     True
5    False
Name: Dog Breed, dtype: bool

In [45]:
not_poodle = df[df['Dog Breed'] != 'Poodle']
not_poodle

  Dog Name             Owner Name         Dog Breed         Status  Age
0    Bayes               DataCamp  Golden Retriever  Still Missing    1
1  Sigmoid                    NaN         Dachshund  Still Missing    2
2   Sparky             Dr. Apache     Border Collie          Found    3
3  Theorem  Joseph-Louis Lagrange    French Bulldog          Found    4
4      Ned           Tim Oliphant          Shih Tzu  Still Missing    2